const questions = [
  { question: "What is your favorite sport to watch and why?", category: 'sport' },
  { question: "Have you ever played a sport? If so, which one(s) and for how long?", category: 'sport' },
  { question: "Do you prefer team sports or individual sports and why?", category: 'sport' },
  { question: "Who is your favorite athlete and why?", category: 'sport' },
  { question: "What is your favorite sports moment of all time?", category: 'sport' },
  { question: "What do you do for a living?", category: "career" },
  { question: "What inspired you to pursue your current career?", category: "career" },
  { question: "What do you like most about your job?", category: "career" },
  { question: "What do you find challenging about your job?", category: "career" },
  { question: "What are your career goals for the next five years?", category: "career" },
  { question: "Where is the most interesting place you've ever been to and why?", category: "travel" },
  { question: "What is your favorite way to travel and why?", category: "travel" },
  { question: "What's on your travel bucket list and why?", category: "travel" },
  { question: "Do you prefer to travel alone or with others and why?", category: "travel" },
  { question: "What's the most memorable experience you've had while traveling?", category: "travel" },
  { question: "What is your favorite type of music and why?", category: "music" },
  { question: "Who is your favorite musical artist and why?", category: "music" },
  { question: "Have you ever been to a concert or music festival? If so, which one(s) and what was your favorite part?", category: "music" },
  { question: "What is your favorite song of all time and why?", category: "music" },
  { question: "Do you play any musical instruments? If so, which one(s)?", category: "music" },
  { question: "Are you sunrise, daylight, twilight, or night? Please share why you picked your time of day. ", category: "career" },
  { question: "Are you summer, fall, spring, or winter? Please share why.", category: "free" },
  { question: "What is the best piece of advice you have ever gotten at work?", category: "career" },
  { question: "What’s the best piece of advice you’ve ever been given?", category: "free" },
  { question: "What do your family and friends think you do all day?", category: "career" },
  { question: "Have you ever won something as a team?", category: "career" },
  { question: "What’s the hardest part about working virtually for you? The easiest?", category: "career" },
  { question: "Be honest, how often do you work from bed?", category: "career" },
  { question: "How do you stay productive and motivated working virtually?", category: "career" },
  { question: "What does your typical work from home uniform look like?", category: "career" },
  { question: "What’s one thing we could do to improve our virtual meetings?", category: "free" },
  { question: "What’s your favorite flower or plant?", category: "free" },
  { question: "What is your favorite meal to cook and why?", category: "free" },
  { question: "If you could instantly become an expert in something, what would it be? Why?", category: "career" },
  { question: "If you could rename yourself, what name would you pick?", category: "free" },
  { question: "What’s something new you’ve learned about yourself in the last three months?", category: "free" },
  { question: "What’s a word or phrase in another language (or your own) that you really like?", category: "free" },
  { question: "What are you excited about this week?", category: "career" },
  { question: "What’s one thing you’ve been procrastinating on and can’t finish?", category: "free" },
  { question: "What’s the last thing you completed that you’re proud of?", category: "free" },
  { question: "Have you learned any useful productivity hacks recently?", category: "career" },
  { question: "Show us something in your space that you really like.", category: "free" },
  { question: "What’s one skill that helps you successfully work remotely?", category: "career" },
  { question: "Do you have a favorite mug? Let us see it and explain why you love it.", category: "free" },
  { question: "When you’re feeling stressed, how do you deal with it?", category: "career" },
  { question: "What’s something you admire about the people on our team?", category: "career" },
  { question: "What do you value most in a friendship?", category: "free" },
  { question: "What’s one characteristic you admire in others?", category: "free" },
  { question: "How would your best friend describe you?", category: "free" },
  { question: "What’s a new habit or practice you’re trying to cultivate?", category: "free" },
  { question: "What’s your favorite quote?", category: "free" }
  
]
